DECLARE @RECNO_BASE BIGINT;
SET @RECNO_BASE = ISNULL((SELECT MAX(R_E_C_N_O_) FROM ZC3010), 0);

;WITH src AS (
    SELECT * FROM (VALUES
    ) AS v(ZC3_FILIAL,ZC3_STATUS,ZC3_TIPO,ZC3_PROD,ZC3_DATA,ZC3_LOCAL,ZC3_LOTE,ZC3_END,ZC3_QTD,ZC3_OP,ZC3_ROTINA,ZC3_PROCES,ZC3_YSIC,ZC3_CC)
),
num AS (
    SELECT ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS rn, *
    FROM src
)
INSERT INTO ZC3010 (
    R_E_C_N_O_, ZC3_TIPO, ZC3_FILIAL, ZC3_STATUS,
    ZC3_PROD, ZC3_DATA, ZC3_LOCAL, ZC3_LOTE,
    ZC3_QTD, ZC3_END, ZC3_OP,
    ZC3_ROTINA, ZC3_PROCES, ZC3_YSIC, ZC3_CC
)
SELECT
    @RECNO_BASE + rn,
    ZC3_TIPO, ZC3_FILIAL, ZC3_STATUS,
    ZC3_PROD, ZC3_DATA, ZC3_LOCAL, ZC3_LOTE,
    CAST(ZC3_QTD AS DECIMAL(18,7)),
    ISNULL(ZC3_END, ''),
    ZC3_OP,
    ZC3_ROTINA, ZC3_PROCES, ZC3_YSIC, ZC3_CC
FROM num;
